  0%|          | 0/8 [00:00<?, ?it/s]Error executing job with overrides: []
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/dfs8/pub/nimel/projects/ibsg/src/simulation/driver.py", line 56, in run_simulation
    dynamics = dynamics(
TypeError: simulation.dynamics.TwoPopulationRD() got multiple values for keyword argument 'imprecise_imitation_beta'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dfs8/pub/nimel/projects/ibsg/src/run_simulations.py", line 18, in main
    trials = run_trials(config)
  File "/dfs8/pub/nimel/projects/ibsg/src/simulation/driver.py", line 27, in run_trials
    return run_trials_multiprocessing(config, population_init_betas)
  File "/dfs8/pub/nimel/projects/ibsg/src/simulation/driver.py", line 50, in run_trials_multiprocessing
    return [async_result.get() for async_result in tqdm(async_results)]
  File "/dfs8/pub/nimel/projects/ibsg/src/simulation/driver.py", line 50, in <listcomp>
    return [async_result.get() for async_result in tqdm(async_results)]
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: simulation.dynamics.TwoPopulationRD() got multiple values for keyword argument 'imprecise_imitation_beta'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
  0%|          | 0/8 [00:00<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/dfs8/pub/nimel/projects/ibsg/src/plot.py", line 40, in main
    sim_data = pd.read_csv(sim_fn)
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/data/homezvol0/nimel/.conda/envs/ibsg/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/dfs8/pub/nimel/projects/ibsg/outputs/states=10/signals=10/prior=-8/dist=squared_dist/meaning_certainty=0/dynamics=two_population_rd/population_size=None/num_trials=8/seed=42/discr_need=1.0/simulation_points.csv'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

real	0m23.369s
user	0m12.840s
sys	0m3.801s
